name: code_gen_tester
version: 0.0.1
environment:
    sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
    source_gen: ^0.9.4+7
    build: '>=1.1.2 <2.0.0'
    analyzer: '>=0.35.4 <0.40.0'
    test: ^1.9.4
    dart_style:
    pedantic:
    build_runner: 1.7.2
    build_test: ^0.10.11
