# Created with package:mono_repo v1.2.2-dev
language: dart

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: stable - DIR: functional_widget - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings lib test]"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
      env: PKG="functional_widget"
      dart: stable
    - stage: unit_test
      name: "SDK: stable - DIR: functional_widget - TASKS: [pub run test, pub run test_coverage, bash <(curl -s https://codecov.io/bash)]"
      script: ./tool/travis.sh test command_0 command_1
      env: PKG="functional_widget"
      dart: stable
    - stage: analyzer_and_format
      name: "SDK: stable - DIR: functional_widget_annotation - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings lib]"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
      env: PKG="functional_widget_annotation"
      dart: stable

stages:
  - analyzer_and_format
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - functional_widget/.dart_tool/build
