name: functional_widget
description: A code generator that generates widget classes from their implementation as a function.
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/functional_widget/tree/master/functional_widget
version: 0.7.2

environment:
    sdk: '>=2.6.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    functional_widget_annotation: ^0.5.1
    source_gen: ^0.9.4+7
    build_config: '>=0.3.1+4 <1.0.0'
    code_builder: '>=3.2.0 <4.0.0'
    build: '>=1.1.2 <2.0.0'
    analyzer: '>=0.35.4 <0.40.0'
    meta: ^1.1.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    test: ^1.9.4
    mockito: 4.0.0
    dart_style: '>=1.2.4 <1.4.0'
    pedantic:
    build_runner: 1.7.2
    test_coverage: ^0.4.0
    code_gen_tester:
        path: ../code_gen_tester
